import type { NextPage } from 'next'
import Head from 'next/head'
import LinkToApp from '../components/LinkToApp/LinkToApp'
import Content from '../components/MainContent/Content'
import styles from '../styles/index.module.scss'
const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Dobro Coffee</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="favicon.ico" />
			</Head>

			<main>
				<Content />
			</main>

			<footer className={styles.footer}>
				<LinkToApp/>
			</footer>
		</>
	)
}

export default Home
