import Head from 'next/head'
import { motion } from 'framer-motion'

const Yandex = () => {
	return (
		<>
			<Head>
				<title>Yandex Отзывы</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<motion.div
				initial={{ y: 200, opacity: 0 }}
				animate={{ y: 0, opacity: 1 }}
				transition={{ duration: 2 }}
				style={{ zIndex: 1010 }}
			>
				<div>
					<div>
						<iframe
							title="Yandex"
							src="https://yandex.ru/maps-reviews-widget/113115524349?comments"
						></iframe>
						<a
							href="https://yandex.ru/maps/org/dobro_kofe/113115524349/"
							target="_blank"
							rel="noreferrer"
						>
							ДоБро кофе на карте Севастополя — Яндекс Карты
						</a>
					</div>
				</div>
			</motion.div>
		</>
	)
}

export default Yandex
